### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by pakodx** [ZeeRooo/MaterialFBook#158]
Yesterday the app started having another issue
It keeps crashing every few minutes, even when it's not open
I tried to force stop it, but it starts by itself again and continues crashing

Android 5.1

**Comment by pakodx** [comment]
Now the app crashes:
-when sharing something
-Scrolling
-when posting something
-randomly
-when opening some settings
-when opening some pages

**Comment by creativetrendsapps** [comment]
@pakodx, that's with notifications on?

**Comment by creativetrendsapps** [comment]
I believe it's the library I mentioned earlier.

**Comment by ZeeRooo** [comment]
@creativetrendsapps You mean jsoup?

**Comment by LoneFenris** [comment]
Would be nice if there were an option to turn crash reports off, by the way.

**Comment by creativetrendsapps** [comment]
@LoneFenris , you don't want the dev to know when there's a crash or what caused it?

**Comment by LoneFenris** [comment]
I want to have control over data that I would send out.

**Comment by LoneFenris** [comment]
Particularly when the crash reports are not anonymous.

**Comment by creativetrendsapps** [comment]
@LoneFenris , have you seen anything that are in the crash reports? It's basic device information... Along with a stack track of. Besides your email address... The reports are anonymous. But, ok 🤷🏾‍♂️.

**Comment by pakodx** [comment]
@lobefenris if you disable Gmail it stops. I disabled it today after sending probably more than a hundred reports since it wouldn't work and would crash every 3 minutes or so

Tbh I think there's no harm in sending it, accessing Facebook is probably giving up way more of your privacy than just some basic device info and the crash report

**Comment by tgp1994** [comment]
I'm seeing consistent crashes when trying to open my messages, I'm assuming this is related? Using latest on F-Droid (2.7.5).

**Comment by ZeeRooo** [comment]
@creativetrendsapps I'm using Jsoup 1.11.2 in my new project and is working fine on all my friends devices. The crash report from pakodx says... 
`java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:304)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.IllegalStateException: Couldn't read row 0, col 3 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
at android.database.CursorWindow.nativeGetString(Native Method)
at android.database.CursorWindow.getString(CursorWindow.java:438)
at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
at me.zeeroooo.materialfb.Notifications.NotificationsJIS.onHandleWork(NotificationsJIS.java:70)
at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:391)
at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:382)
at android.os.AsyncTask$2.call(AsyncTask.java:292)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 3 more
java.lang.IllegalStateException: Couldn't read row 0, col 3 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
at android.database.CursorWindow.nativeGetString(Native Method)
at android.database.CursorWindow.getString(CursorWindow.java:438)
at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
at me.zeeroooo.materialfb.Notifications.NotificationsJIS.onHandleWork(NotificationsJIS.java:70)
at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:391)
at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:382)
at android.os.AsyncTask$2.call(AsyncTask.java:292)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)`

**Comment by tgp1994** [comment]
It seems like the error is centered somewhere around [here.](https://github.com/ZeeRooo/MaterialFBook/blob/479376e824db44b2a45a6e14a137056ed66c6be6/app/src/main/java/me/zeeroooo/materialfb/Notifications/NotificationsJIS.java#L70) I'd be interested to see what the contents of the DB query are when `db.getListContents()` is called.

**Comment by ZeeRooo** [comment]
Yes, you are right. _getListContents_ just select everything from the table (SELECT * FROM....). Anyway im reworking the database and switching from * to BL which is the column with the black list words.

**Comment by ZeeRooo** [comment]
@pakodx Can you test the app and check if the crash is fixed?

**Comment by ZeeRooo** [comment]
[MFB_alpha.zip](https://github.com/ZeeRooo/MaterialFBook/files/1926232/MFB_alpha.zip)
@pakodx Can you test this version? _GitHub doesnt support .apk so i have had to compress it_

**Comment by pakodx** [comment]
@ZeeRooo

I just tried it, it still crashed when I opened it and every few minutes

Here's the crash report:

USER_COMMENT=
ANDROID_VERSION=5.1
APP_VERSION_NAME=a3.7.9
BRAND=motorola
PHONE_MODEL=XT1040
CUSTOM_DATA=
STACK_TRACE=java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: android.database.sqlite.SQLiteException: no such column: BL (code 1): , while compiling: SELECT BL FROM mfb_table
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1316)
	at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1255)
	at me.zeeroooo.materialfb.Notifications.NotificationsJIS.onHandleWork(NotificationsJIS.java:66)
	at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:391)
	at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:382)
	at android.os.AsyncTask$2.call(AsyncTask.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 3 more
android.database.sqlite.SQLiteException: no such column: BL (code 1): , while compiling: SELECT BL FROM mfb_table
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1316)
	at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1255)
	at me.zeeroooo.materialfb.Notifications.NotificationsJIS.onHandleWork(NotificationsJIS.java:66)
	at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:391)
	at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:382)
	at android.os.AsyncTask$2.call(AsyncTask.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

**Comment by ZeeRooo** [comment]
@pakodx 
[MFB_3.9.zip](https://github.com/ZeeRooo/MaterialFBook/files/1936223/MFB_3.9.zip)

**Comment by pakodx** [comment]
![screenshot_2018-04-22-21-03-35](https://user-images.githubusercontent.com/38252669/39101509-e01217d2-4670-11e8-9118-7d2bb9b1b6f3.png)
Thank you but it won't let me install

**Comment by pakodx** [comment]
Is there a way to back up my bookmarks so I can try a clean install?

**Comment by ZeeRooo** [comment]
@pakodx And now? 
[MFB_alpha-3.9.zip](https://github.com/ZeeRooo/MaterialFBook/files/1936387/MFB_alpha-3.9.zip)

**Comment by pakodx** [comment]
It worked! Thank you so much!!
I browsed for a bit and it didn't crash
Chat is working too!

The only issue I noticed was that videos and images are taking a very long time to load and sometimes they don't load at all.

BTW, is there a different way to get out of the full size screen?
Whenever I press back it throws me back at the timeline instead of putting me back at the page I was.

Also, can you make the images and videos go to root:/pictures/MaterialFBook (or something like that ) instead of just the pictures folder? Would help to keep it more organized

**Comment by ZeeRooo** [comment]
Ok, so the v3.8.0 is fully working.
And i moved the pictures folder to <storage>/Pictures/MaterialFBook (same for movies).
