### ISSUE TITLE
Crash on selecting notification settings

### ISSUE THREAD

**Issue by samon53** [ZeeRooo/MaterialFBook#173]
USER_COMMENT=
ANDROID_VERSION=8.0.0
APP_VERSION_NAME=3.8.1
BRAND=OnePlus
PHONE_MODEL=ONEPLUS A3003
CUSTOM_DATA=
STACK_TRACE=android.database.sqlite.SQLiteException: no such column: BL (code 1): , while compiling: SELECT BL FROM mfb_table
at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1343)
at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1282)
at me.zeeroooo.materialfb.Fragments.NotificationsSettingsFragment.onCreate(NotificationsSettingsFragment.java:50)
at android.app.Fragment.performCreate(Fragment.java:2593)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1234)
at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2415)
at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2194)
at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2148)
at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2049)
at android.app.FragmentManagerImpl$1.run(FragmentManager.java:718)
at android.os.Handler.handleCallback(Handler.java:789)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6809)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by miiichael** [comment]
Same here. Also note that the email error handler doesn't supply a recipient email address (or offer an opportunity to supply a user comment).

USER_COMMENT=
ANDROID_VERSION=7.0
APP_VERSION_NAME=3.8.1
BRAND=lge
PHONE_MODEL=LG-H990
CUSTOM_DATA=
STACK_TRACE=android.database.sqlite.SQLiteException: no such column: BL (code 1): , while compiling: SELECT BL FROM mfb_table
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:974)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:585)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:726)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1429)
	at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1368)
	at me.zeeroooo.materialfb.Fragments.NotificationsSettingsFragment.onCreate(NotificationsSettingsFragment.java:50)
	at android.app.Fragment.performCreate(Fragment.java:2344)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:949)
	at android.app.BackStackRecord.setLastIn(BackStackRecord.java:857)
	at android.app.BackStackRecord.calculateFragments(BackStackRecord.java:897)
	at android.app.BackStackRecord.run(BackStackRecord.java:727)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1582)
	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:483)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6247)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)

**Comment by reedcourty** [comment]
Same on my phone, but with different stacktrace:

```
USER_COMMENT=
ANDROID_VERSION=6.0
APP_VERSION_NAME=3.8.1
BRAND=lge
PHONE_MODEL=LG-H815
CUSTOM_DATA=
STACK_TRACE=java.util.UnknownFormatConversionException: Conversion: .
at java.util.Formatter$FormatSpecifierParser.unknownFormatConversionException(Formatter.java:2321)
at java.util.Formatter$FormatSpecifierParser.parsePrecision(Formatter.java:2389)
at java.util.Formatter$FormatSpecifierParser.parseArgumentIndexAndFlags(Formatter.java:2363)
at java.util.Formatter$FormatSpecifierParser.parseFormatToken(Formatter.java:2298)
at java.util.Formatter.doFormat(Formatter.java:1071)
at java.util.Formatter.format(Formatter.java:1042)
at java.util.Formatter.format(Formatter.java:1011)
at java.lang.String.format(String.java:1554)
at java.lang.String.format(String.java:1528)
at android.preference.ListPreference.getSummary(ListPreference.java:169)
at android.preference.Preference.onBindView(Preference.java:558)
at android.preference.Preference.getView(Preference.java:495)
at android.preference.PreferenceGroupAdapter.getView(PreferenceGroupAdapter.java:246)
at android.widget.AbsListView.obtainView(AbsListView.java:2389)
at android.widget.ListView.makeAndAddView(ListView.java:1878)
at android.widget.ListView.fillDown(ListView.java:705)
at android.widget.ListView.fillFromTop(ListView.java:766)
at android.widget.ListView.layoutChildren(ListView.java:1673)
at android.widget.AbsListView.onLayout(AbsListView.java:2191)
at android.view.View.layout(View.java:16662)
at android.view.ViewGroup.layout(ViewGroup.java:5439)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
at android.view.View.layout(View.java:16662)
at android.view.ViewGroup.layout(ViewGroup.java:5439)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
at android.view.View.layout(View.java:16662)
at android.view.ViewGroup.layout(ViewGroup.java:5439)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
at android.view.View.layout(View.java:16662)
at android.view.ViewGroup.layout(ViewGroup.java:5439)
at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1191)
at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:876)
at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:895)
at android.view.View.layout(View.java:16662)
at android.view.ViewGroup.layout(ViewGroup.java:5439)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
at android.view.View.layout(View.java:16662)
at android.view.ViewGroup.layout(ViewGroup.java:5439)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
at android.view.View.layout(View.java:16662)
at android.view.ViewGroup.layout(ViewGroup.java:5439)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
at android.view.View.layout(View.java:16662)
at android.view.ViewGroup.layout(ViewGroup.java:5439)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
at android.view.View.layout(View.java:16662)
at android.view.ViewGroup.layout(ViewGroup.java:5439)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2720)
at android.view.View.layout(View.java:16662)
at android.view.ViewGroup.layout(ViewGroup.java:5439)
at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2202)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1955)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1125)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6100)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
at android.view.Choreographer.doCallbacks(Choreographer.java:670)
at android.view.Choreographer.doFrame(Choreographer.java:606)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5525)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
```

**Comment by yarons** [comment]
Tested in 3.8.6, no crashing but there's no settings screen.
